apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qama73byg-go
  janus-idp.io/tekton: qama73byg-go
  backstage.io/kubernetes-id: qama73byg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qama73byg-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
