apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qama73byg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qama73byg-go 
  name: qama73byg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qama73byg-go 
